#!/usr/bin/env ruby

require 'cloud_compose'
require 'cloud_compose/cli'

COMMANDS = {
  'build' => CloudCompose::Cli::Build,
  'version' => ->(_) { STDOUT.puts CloudCompose::VERSION },
  'help' => ->(_) { STDERR.puts HELP_MESSAGE },
  'print' => CloudCompose::Cli::Print
}.freeze

HELP_MESSAGE = <<~EOF.freeze
  CloudCompose #{CloudCompose::VERSION} Help

  Commands
  #{COMMANDS.keys.map { |k| "  - #{k}" }.join("\n")}
EOF

command_name = ARGV.shift

command_name = 'help' if command_name.nil? || command_name.empty?

begin
  command = COMMANDS.fetch(command_name)
  command.call(ARGV)
rescue StandardError => error
  STDERR.puts "Error: #{error}"
  exit(1)
end
